service: example-sls
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: first_endpoint/{name}
          method: get
