service: password-strength

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

package:
  exclude:
    - node_modules/**

functions:
  password:
    handler: handler.password
    events: 
      - http:
          path: password/{password}
          method: get
